name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      
      - name: Setup Python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e  # v2
        with:
          python-version: 3.11.4
      
      - name: Install dependencies
        run: pip install black ruff

      - name: Run Black
        run: black . --check --diff 

      - name: Run Ruff
        run: ruff check .
