name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face (DeepfloydIF)
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: lunarflu/huggingbots
        huggingface_repo_id: lunarflu/deepfloydif-bot
        repo_type: space
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN_WRITE }}
        subdirectory: deepfloydif
        files: |
          app.py: lunarflu/deepfloydIF-bot
          requirements.txt: lunarflu/deepfloydIF-bot
