name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face (Falcon180b)
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: huggingface/discord-bots
        huggingface_repo_id: huggingface-projects/falcon180b-bot
        repo_type: space
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN_WRITE }}
        subdirectory: falcon180b
        files: |
          app.py: huggingface-projects/falcon180b-bot
          requirements.txt: huggingface-projects/falcon180b-bot
