name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face (Falcon180b)
      uses: nateraw/huggingface-sync-action@54e4f55015a52747b4e2a5c9f2ee1056880cdd42 # v0.0.5
      with:
        github_repo_id: huggingface/discord-bots
        huggingface_repo_id: huggingface-projects/falcon180b-bot
        repo_type: space
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN_WRITE }}
        subdirectory: falcon180b
        files: |
          app.py: huggingface-projects/falcon180b-bot
          requirements.txt: huggingface-projects/falcon180b-bot
